title: Portfolio di Francesco Cerisano
email: francesco.cerisano@example.com
description: >
  Benvenuti nel mio portfolio professionale. Qui potrete trovare progetti, articoli e informazioni sul mio percorso e le mie competenze nel campo dello sviluppo software e design.
baseurl: "" # Questo è utile se il tuo sito non è alla radice del dominio.
url: "http://francescocerisano.github.io" # Sostituisci con il tuo vero URL se disponibile.
